#ifndef UTL_CONSOLE_H_OLD
#define UTL_CONSOLE_H_OLD

#include <uso/console.h>

#define UTL_COLOR_BLACK   USO_COLOR_BLACK
#define UTL_COLOR_RED     USO_COLOR_RED
#define UTL_COLOR_GREEN   USO_COLOR_GREEN
#define UTL_COLOR_YELLOW  USO_COLOR_YELLOW
#define UTL_COLOR_BLUE    USO_COLOR_BLUE
#define UTL_COLOR_MAGENTA USO_COLOR_MAGENTA
#define UTL_COLOR_CYAN    USO_COLOR_CYAN
#define UTL_COLOR_WHITE   USO_COLOR_WHITE
#define UTL_COLOR_NORMAL  USO_COLOR_NORMAL

#define utl_colorline uso_colorline

#endif
