#ifndef VIS_H
#define VIS_H

#include "defines.h"

#include "state.h"
#include "attribute.h"
#include "background.h"
#include "bin.h"
#include "camera.h"
#include "clipspace.h"
#include "collection.h"
#include "collight.h"
#include "colobject.h"
#include "colscene.h"
#include "engine.h"
#include "entity.h"
#include "eyespace.h"
#include "group.h"
#include "item.h"
#include "light.h"
#include "listener.h"
#include "node.h"
#include "nodelist.h"
#include "object.h"
#include "scene.h"
#include "shape.h"
#include "space.h"
#include "strategy.h"
#include "switch.h"
#include "utils.h"
#include "transform.h"
#include "vertexarray.h"
#include "wrlspace.h"

#include "back/backcolor.h"

#include "eng/statesequence.h"
#include "eng/kinematics.h"
#include "eng/texanimator.h"
#include "eng/shpswitcher.h"

#include "light/dlight.h"
#include "light/plight.h"
#include "light/slight.h"

#include "loadr/mdlloader.h"
#include "loadr/mshloader.h"

#include "shp/cube.h"
#include "shp/grid.h"
#include "shp/hplane.h"
#include "shp/line.h"
#include "shp/mesh.h"
#include "shp/pipe.h"
#include "shp/sphere.h"
#include "shp/terrain.h"
#include "shp/triangle.h"
#include "shp/volume.h"
#include "shp/text.h"

#include "state/stategroup.h"
#include "state/stateswitch.h"
#include "state/color.h"
#include "state/fog.h"
#include "state/material.h"
#include "state/texture.h"
#include "state/shader.h"
#include "state/params.h"
#include "state/glslshader.h"
#include "state/texcombiner.h"

#include "strat/collector.h"
#include "strat/immediate.h"
#include "strat/retained.h"
#include "strat/interceptor.h"
#include "strat/itemfinder.h"
#include "strat/accel.h"
#include "strat/accel/chain.h"
//#include "strat/coll/depthsort.h"
#include "strat/coll/matsort.h"
#include "strat/coll/transpmatsort.h"
#include "strat/intercept/counter.h"
#include "strat/render/loadlights.h"
#include "strat/render/render.h"
#include "strat/render/selrender.h"
#include "strat/render/transprender.h"
#include "strat/render/flexrender.h"

#include "writers/meshwriter.h"
#include "writers/mshwriter.h"

#endif
